# Generated by Django 5.2.6 on 2025-09-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyName', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
