# Generated by Django 5.2.6 on 2025-09-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyinfo',
            name='adjective',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyinfo',
            name='names',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyinfo',
            name='noun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyinfo',
            name='pronouns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyinfo',
            name='verbcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storyinfo',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='storyinfo',
            name='storyName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
