# Generated by Django 5.2.6 on 2025-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storiess', '0002_storyinfo_adjective_storyinfo_names_storyinfo_noun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyinfo',
            name='story',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storyinfo',
            name='storyURL',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
