# Generated by Django 5.2.6 on 2025-09-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbie',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
