# Generated by Django 5.2.6 on 2025-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hobbies', '0002_alter_hobbie_image_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobbie',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
